import type { Language } from "@/types";

export const LANGUAGE_LABELS: { [key: string]: string } = {
  th: "ไทย",
  zh: "中文",
  hi: "हिन्दी",
  ur: "اردو",
  bn: "বাংলা",
  pa: "ਪੰਜਾਬੀ",
  am: "አማርኛ",
  ha: "Hausa",
  fa: "فارسی",
  he: "עברית",
  ja: "日本語",
  ko: "한국어",
  si: "සිංහල",
  ta: "தமிழ்",
  hu: "Magyar",
  mn: "Монгол",
  tr: "Türkçe",
  pl: "Polski",
  ro: "Română",
  ca: "Català",
  cs: "Čeština",
  ka: "ქართული",
  de: "Deutsch",
  en: "English",
  es: "Español",
  eu: "Euskara",
  ru: "Русский",
  tl: "Tagalog",
  zu: "isiZulu",
  ar: "العربية",
  el: "Ελληνικά",
  fr: "Français",
  it: "Italiano",
  bg: "Български",
  pt: "Português",
  tk: "Türkmençe",
  sw: "Kiswahili",
  uk: "Українська",
  vi: "Tiếng Việt",
  my: "မြန်မာဘာသာ",
  ms: "Bahasa Melayu",
  id: "Bahasa Indonesia",
  sr: "Српски",
  "zh-hk": "中文 (香港)",
  "en-us": "English (US)",
  "en-uk": "English (UK)",
  "es-419": "Español (Latinoamérica)",
  "es-la": "Español (LATAM)",
  "es-mx": "Español (México)",
  "pt-br": "Português (Brasil)",
};

export const LANGUAGE_OPTIONS: Language[] = [
  { id: "en", label: "English" },
  { id: "pt-br", label: "Português (BR)" },
  { id: "es", label: "Español" },
  { id: "ja", label: "日本語" },
  { id: "zh", label: "中文" },
  { id: "ru", label: "Русский" },
  { id: "fr", label: "Français" },
  { id: "de", label: "Deutsch" },
  { id: "ar", label: "العربية" },
  { id: "en-us", label: "English (US)" },
  { id: "es-mx", label: "Español (México)" },
  { id: "it", label: "Italiano" },
  { id: "ko", label: "한국어" },
  { id: "vi", label: "Tiếng Việt" },
  { id: "hi", label: "हिन्दी" },
  { id: "id", label: "Bahasa Indonesia" },
  { id: "th", label: "ไทย" },
  { id: "ms", label: "Bahasa Melayu" },
  { id: "bn", label: "বাংলা" },
  { id: "ta", label: "தமிழ்" },
  { id: "tr", label: "Türkçe" },
  { id: "pl", label: "Polski" },
  { id: "uk", label: "Українська" },
  { id: "pa", label: "ਪੰਜਾਬੀ" },
  { id: "sw", label: "Kiswahili" },
  { id: "ro", label: "Română" },
  { id: "fa", label: "فارسی" },
  { id: "el", label: "Ελληνικά" },
  { id: "cs", label: "Čeština" },
  { id: "hu", label: "Magyar" },
  { id: "am", label: "አማርኛ" },
  { id: "bg", label: "Български" },
  { id: "eu", label: "Euskara" },
  { id: "mn", label: "Монгол" },
  { id: "tk", label: "Türkmençe" },
  { id: "my", label: "မြန်မာဘာသာ" },
  { id: "si", label: "සිංහල" },
  { id: "ha", label: "Hausa" },
  { id: "tl", label: "Tagalog" },
  { id: "ur", label: "اردو" },
  { id: "zh-hk", label: "中文 (香港)" },
  { id: "ca", label: "Català" },
  { id: "en-uk", label: "English (UK)" },
  { id: "es-la", label: "Español (LATAM)" },
  { id: "zu", label: "isiZulu" },
  { id: "pt", label: "Português" },
];
