import type { Suggestion } from "@/types";

export const SHOUNENS: Suggestion[] = [
  {
    name: "One Piece",
    extra_name: "",
    description: `Gol D. Roger, a man referred to as the "Pirate King," is set to be executed by the World Government. But just before his demise, he confirms the existence of a great treasure, One Piece, located somewhere within the vast ocean known as the Grand Line. Announcing that One Piece can be claimed by anyone worthy enough to reach it, the Pirate King is executed and the Great Age of Pirates begins.

		Twenty-two years later, a young man by the name of Monkey D. Luffy is ready to embark on his own adventure, searching for One Piece and striving to become the new Pirate King. Armed with just a straw hat, a small boat, and an elastic body, he sets out on a fantastic journey to gather his own crew and a worthy ship that will take them across the Grand Line to claim the greatest status on the high seas.`,
    folder_name: "one-piece",
    cover:
      "https://mangadex.org/covers/a1c7c817-4e59-43b7-9365-09675a149a6f/17f8c157-ae5c-4702-a762-11bc2c8b8c64.jpg",
    sources: [
      {
        source_id: "a1c7c817-4e59-43b7-9365-09675a149a6f",
        source_name: "MangaDex",
        link: "https://mangadex.org/title/a1c7c817-4e59-43b7-9365-09675a149a6f/one-piece",
        language: ["English", "Portugues", "Espanhol", "Italiano"],
      },
      {
        source_id: "5/one-piece",
        source_name: "TCB",
        link: "https://tcbscans.me/mangas/5/one-piece",
        language: ["English"],
      },
      {
        source_id: "one-piece",
        source_name: "MangaSee",
        link: "https://mangasee123.com/manga/one-piece",
        language: ["English"],
      },
      {
        source_id: "one-piece-3",
        source_name: "MangaReader",
        link: "https://mangareader.to/one-piece-3",
        language: ["English", "Portugues", "Espanhol", "日本語", "French"],
      },
    ],
  },
  // {
  //   name: "Sakamoto Days",
  //   folder_name: "sakamoto-days-3279",
  //   cover:
  //     "https://img.mreadercdn.com/_m/300x400/100/f6/c6/f6c6530eb340af98a79f7a994931d621/f6c6530eb340af98a79f7a994931d621.jpg",
  //   source: "MangaReaderTo",
  //   source_id: "sakamoto-days-3279",
  //   type: "manga",
  //   extra_name: "",
  //   title_color: "",
  //   card_color: "",
  //   grade: 0,
  //   author: "Unknow",
  //   is_ultra_favorite: false,
  //   description: "",
  //   link: "https://mangareader.to/sakamoto-days-3279",
  //   marks: [],
  //   readeds: [],
  // },
  // {
  //   id: 317,
  //   user_id: 1,
  //   name: "HUNTER x HUNTER",
  //   folder_name: "HUNTER%20x%20HUNTER",
  //   cover:
  //     "https://mangadex.org/covers/db692d58-4b13-4174-ae8c-30c515c0689c/a1686843-1414-45e4-a4b7-425d58356042.jpg",
  //   source: "MangaDex",
  //   source_id: "db692d58-4b13-4174-ae8c-30c515c0689c",
  //   type: "manga",
  //   extra_name: "Аулаушы × Аулаушы",
  //   title_color: "",
  //   card_color: "",
  //   grade: 0,
  //   author: "Unknow",
  //   is_ultra_favorite: false,
  //   description:
  //     "Hunters are a special breed, dedicated to tracking down treasures, magical beasts, and even other men. But such pursuits require a license, and less than one in a hundred thousand can pass the grueling qualification exam. Those who do pass gain access to restricted areas, amazing stores of information, and the right to call themselves Hunters.",
  //   link: "https://mangadex.org/title/db692d58-4b13-4174-ae8c-30c515c0689c",
  //   marks: [],
  //   readeds: [],
  // },
  // {
  //   id: 315,
  //   user_id: 1,
  //   name: "Undead Unluck",
  //   folder_name: "undead-unluck-7025",
  //   cover:
  //     "https://img.mreadercdn.com/_m/300x400/100/90/52/9052c67b391aded0d76af925996a40f1/9052c67b391aded0d76af925996a40f1.jpg",
  //   source: "MangaReaderTo",
  //   source_id: "undead-unluck-7025",
  //   type: "manga",
  //   extra_name: "",
  //   title_color: "",
  //   card_color: "",
  //   grade: 0,
  //   author: "Unknow",
  //   is_ultra_favorite: false,
  //   description: "",
  //   link: "https://mangareader.to/undead-unluck-7025",
  //   marks: [],
  //   readeds: [],
  // },
  // {
  //   id: 93,
  //   user_id: 1,
  //   name: "Black Clover",
  //   folder_name: "Black-Clover",
  //   cover: "https://temp.compsci88.com/cover/Black-Clover.jpg",
  //   source: "MangaSee",
  //   source_id: "Black-Clover",
  //   type: "manga",
  //   extra_name: "Black Clover",
  //   title_color: "",
  //   card_color: "",
  //   grade: 0,
  //   author: "TABATA Yuuki",
  //   is_ultra_favorite: false,
  //   description: "",
  //   link: "",
  //   marks: [],
  //   readeds: [],
  // },
  // {
  //   id: 36,
  //   user_id: 1,
  //   name: "One Piece",
  //   folder_name: "one-piece",
  //   cover:
  //     "https://mangadex.org/covers/a1c7c817-4e59-43b7-9365-09675a149a6f/17f8c157-ae5c-4702-a762-11bc2c8b8c64.jpg",
  //   source: "TCB",
  //   source_id: "5/one-piece",
  //   type: "manga",
  //   extra_name: "",
  //   title_color: "",
  //   card_color: "",
  //   grade: 0,
  //   author: "Unknow",
  //   is_ultra_favorite: true,
  //   description: "",
  //   link: "",
  //   marks: [],
  //   readeds: [],
  // },
  // {
  //   id: 6,
  //   user_id: 1,
  //   name: "Dandadan",
  //   folder_name: "Dandadan",
  //   cover: "https://media.tenor.com/Quspo4-4BzQAAAAM/ken-takakura-okarun.gif",
  //   source: "MangaSee",
  //   source_id: "Dandadan",
  //   type: "manga",
  //   extra_name: "Unknow",
  //   title_color: "",
  //   card_color: "",
  //   grade: 0,
  //   author: "TATSU Yukinobu",
  //   is_ultra_favorite: true,
  //   description:
  //     "Ken Takakura, a boy who is an occult fanatic who doesn't believe in ghosts, and Momo Ayase, a girl who doesn't believe in aliens, encounter overwhelming strangeness that transcends their mutual understanding...! An occult coming-of-age story!",
  //   link: "https://mangasee123.com/manga/Dandadan",
  //   marks: [],
  //   readeds: [],
  // },
];

export const SPORTS: Suggestion[] = [
  {
    name: "Ao Ashi",
    extra_name: "",
    description: "",
    folder_name: "ao-ashi",
    cover:
      "https://img.mreadercdn.com/_m/300x400/100/f6/f7/f6f79a5ff52229db99f5a7389dd697b3/f6f79a5ff52229db99f5a7389dd697b3.jpg",
    sources: [
      {
        source_id: "ao-ashi",
        source_name: "MangaReaderTo",
        link: "https://mangareader.to/ao-ashi",
        language: ["English"],
      },
      {
        source_id: "Ao-Ashi",
        source_name: "MangaSee",
        link: "https://mangasee123.com/manga/ao-ashi",
        language: ["English"],
      },
      {
        source_id: "ao-ashi-2",
        source_name: "MangaReader",
        link: "https://mangareader.to/ao-ashi-2",
        language: ["English"],
      },
    ],
  },
];
