export { MangaSeeDl } from "./mangasee";
export { MangaDexDl } from "./mangadex";
export { TCBScansDl } from "./tcb";
export { MangaReaderToDl } from "./mangareaderto";
export { TaosectDl } from "./taosect";
export { MangaPillDl } from "./mangapill";
export { MangaFireDl } from "./mangafire";
export { WeebCentralDl } from "./weebcentral";
export { MangaLivreDl } from "./mangalivre";
export { MangaSwatDl } from "./mangaswat";
export { ComickDl } from "./comick";
export { MangaParkDl } from "./mangapark"
export { AtsumaruDl } from "./atsumaru"
